name: Build and Push Jira MCP Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-jira-mcp-stdio:
    name: Build and Push jira-mcp-stdio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push jira-mcp-stdio Docker image
        run: |
          docker build -f Dockerfile.stdio -t ghcr.io/${{ github.repository_owner }}/jira-mcp-stdio:latest .
          docker push ghcr.io/${{ github.repository_owner }}/jira-mcp-stdio:latest

  build-jira-mcp-sse:
    name: Build and Push jira-mcp-sse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push jira-mcp-sse Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/jira-mcp-sse:latest .
          docker push ghcr.io/${{ github.repository_owner }}/jira-mcp-sse:latest
